name: build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      config:
        description: Configuration
        required: true
        default: release

env:
  CONFIG: release
  PREMAKE_VERSION: 5.0.0-beta1

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
        cc: [clang]
        include:
          - os: ubuntu-20.04
            osname: linux
          - os: macos-12
            osname: macos

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua
        uses: abel0b/setup-lua@v1
        with:
          lua-version: "5.3.5"

      - name: Install premake
        uses: abel0b/setup-premake@v2.1
        with:
          version: ${{ env.PREMAKE_VERSION }}

      - name: Configure workflow
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo  "CONFIG=${{ github.event.inputs.config }}" >> $GITHUB_ENV

      - name: Generate project file
        run: premake5 gmake2
      
      - name: Compile
        run: make CC=${{ matrix.cc }} config=$CONFIG verbose=1

  build-windows:
    runs-on: windows-2022

    strategy:
      matrix:
        config: [release]
        cc: [cl]

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua
        uses: abel0b/setup-lua@v1
        with:
          lua-version: "5.3.5"

      - name: Install premake
        uses: abel0b/setup-premake@v2.1
        with:
          version: ${{ env.PREMAKE_VERSION }}

      - name: Configure workflow
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo  "CONFIG=${{ github.event.inputs.config }}" >> $env:GITHUB_ENV

      - name: Generate project file
        run: premake5 vs2019

      - name: Compile
        run: |
          .\dev\vsenv.ps1
          msbuild abl.sln -m -p:CLToolExe=${{ matrix.cc }} -p:Configuration=$env:CONFIG
