#include "kobalt/cgen.h"
#include "kobalt/error.h"
#include "kobalt/options.h"
#include "kobalt/memory.h"
#include "kobalt/uid.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define TAB "    "

struct kbcgenctx {
    struct kbsrc* src;
    char* headerpath;
    FILE* cheader;
    char* sourcepath;
    char* include;
    FILE* csource;
};

void emit(FILE* file, char * fmt, ...) {
    va_list args;
    va_start(args, fmt);
    vfprintf(file, fmt, args);
    va_end(args);
} 

static int cgen_aux(struct kbastvisitor * astvisitor) {
    struct kbnode* node = kbast_getnode(astvisitor->ast, astvisitor->cur.nid);
    struct kbcgenctx* cgenctx = astvisitor->ctx;

    switch(node->kind) {
        case NFile:
            break;
        case NFun:
            {
                char* name = kbast_getnode(astvisitor->ast, node->data.fun.id)->data.id.name;
                if (strcmp(name, "main") == 0) {
                    emit(cgenctx->csource, "int main() {\n");
                    emit(cgenctx->csource, TAB "printf(\"Hello world!\\n\");\n");
                    emit(cgenctx->csource, TAB "return 0;\n");
                    emit(cgenctx->csource, "}\n");
                }
            }
            break;
        case NFunParam:
            break;
        case NFunParams:
            break;
        case NFunBody:
            break;
        case NDecl:
            break;
        case NType:
            break;
        case NExpr:
            break;
        case NTerm:
            break;
        case NBinExpr:
            break;
        case NStrLit:
            break;
        case NIntLit:
            break;
        case NFloatLit:
            break;
        case NCharLit:
            break;
        case NCall:
            break;
        case NAssign:
            break;
        case NId:
            break;
        case NCallParams:
            break;
        case NCallParam:
            break;
    }
    return 1;
}

void kbcgenctx_new(struct kbopts* opts, struct kbsrc* src, struct kbcgenctx* cgenctx) {
    cgenctx->src = src;
    
    int srcsize = strlen(opts->cachedir) + 1 + strlen(src->filename);
    
    cgenctx->headerpath = kbmalloc(sizeof(char) * srcsize);
    cgenctx->sourcepath = kbmalloc(sizeof(char) * srcsize);
    
    sprintf(cgenctx->headerpath, "%s/", opts->cachedir);
    int lencachedir = strlen(opts->cachedir);
    int i;
    cgenctx->include = &cgenctx->headerpath[lencachedir+1];
    for(i = 0; i<(int)strlen(src->filename)-3; i++) {
        cgenctx->headerpath[lencachedir+1+i] = (src->filename[i] != DS)? src->filename[i] : '%';
    }
    cgenctx->headerpath[lencachedir+1+i] = '.';
    cgenctx->headerpath[lencachedir+1+i+1] = 'h';
    cgenctx->headerpath[lencachedir+1+i+2] = '\0';
    cgenctx->cheader = fopen(cgenctx->headerpath, "w");
   
    strcpy(cgenctx->sourcepath, cgenctx->headerpath);
    cgenctx->sourcepath[lencachedir+1+i+1] = 'c';
    cgenctx->csource = fopen(cgenctx->sourcepath, "w");
}

void kbcgenctx_del(struct kbcgenctx* cgenctx) {
    fclose(cgenctx->cheader);
    fclose(cgenctx->csource);
    kbfree(cgenctx->headerpath);
    kbfree(cgenctx->sourcepath);
}

int kbcgen(struct kbopts* opts, struct kbsrc* src, struct kbast* ast) {
    struct kberrvec errvec = kberrvec_make();
    
    struct kbcgenctx cgenctx;
    kbcgenctx_new(opts, src, &cgenctx);

    struct kbastvisitor astvisitor;
    kbastvisitor_new(ast, &cgenctx, cgen_aux, &astvisitor);
    

    emit(cgenctx.cheader, "// This file was generated by kbc v%s\n", KBVERSION);
    
    char* headername = kbmalloc(sizeof(char) * (strlen(src->basename) + 2 + 8 + 1));
    memset(headername, 0, sizeof(char) * (strlen(src->basename) + 2 + 8 + 1));
    {
        int cur = 0;
        for(int ii = 0; ii < (int)strlen(src->basename)-3; ++ii) {
            if (src->basename[ii] >= 'a' && src->basename[ii] <= 'z') {
                headername[cur++] = src->basename[ii] + 'A' - 'a';
            }
            else if ((src->basename[ii] >= 'A' && src->basename[ii] <= 'A') || (src->basename[ii] >= '0' && src->basename[ii] <= '9')) {
                headername[cur++] = src->basename[ii];
            }
        }
        headername[cur++] = '_';
        headername[cur++] = '_';
        genuidmaj(headername + cur);
    }

    emit(cgenctx.cheader, "#ifndef __KBH__%s\n", headername);
    emit(cgenctx.cheader, "#define __KBH__%s\n", headername);
    emit(cgenctx.cheader, "#include <stdlib.h>\n");
    emit(cgenctx.cheader, "#include <stdio.h>\n");
    emit(cgenctx.cheader, "#include <stdbool.h>\n");
    emit(cgenctx.cheader, "#include <stdint.h>\n");
    emit(cgenctx.cheader, "#include <math.h>\n");
    kbfree(headername);

    emit(cgenctx.csource, "// This file was generated by kbc v%s\n", KBVERSION);
    emit(cgenctx.csource, "#include \"%s\"\n", cgenctx.include);
    emit(cgenctx.csource, "\n");
    
    kbastvisitor_run(&astvisitor);
   
    emit(cgenctx.cheader, "#endif\n");
 
    kbastvisitor_del(&astvisitor);
    kberrvec_del(&errvec);    
    kbcgenctx_del(&cgenctx);
    return 1;
}
