name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        configuration: [release]

    steps:
    - uses: actions/checkout@v2

    - name: Install premake
      run : |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz
        tar xvzf premake-5.0.0-alpha15-linux.tar.gz
        chmod u+x premake5.exe

    - name: Generate project file
      run: ./premake5 gmake2

    - name: Compile
      run: make config=${{ matrix.config }} -j$(nproc)

  build-windows:
    runs-on: windows-latest

    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin
    steps:
    - uses: actions/checkout@v2

    - name: Install premake
      run: |
        Invoke-WebRequest -Uri "https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-windows.zip" -OutFile "premake-5.0.0-alpha15-windows.zip"
        Expand-Archive -DestinationPath . -Path premake-5.0.0-alpha15-windows.zip


    - name: Generate project file
      run: ./premake5.exe --os=windows vs2019

    - name: Compile
      run: "$MSBUILD_PATH\MSBuild.exe" kobalt.sln -m -p:Configuration=${{ matrix.config }}
