name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        config: [release]
        cc: [gcc, clang]
        include:
          - os: ubuntu-latest
            osname: linux
          - os: macos-latest
            osname: macosx

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua
        uses: xpol/setup-lua@v0.2
        with:
          lua-version: "5.4.0"

      - name: Install premake
        run : |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-${{ matrix.osname }}.tar.gz
          tar xvzf premake-5.0.0-alpha15-${{ matrix.osname }}.tar.gz

      - name: Generate project file
        run: ./premake5 --os=${{ matrix.osname }} gmake2
      
      - name: Generate version header
        run: lua lib/include/kobalt/version.h.lua "$(ls doc/changelog | grep alpha | sed 's/md/${{ github.run_number }}/')" > lib/include/kobalt/version.h

      - name: Compile
        run: make -j$(nproc) CC=${{ matrix.cc }} config=${{ matrix.config }}

      - name: Say hello world
        run: ./bin/${{ matrix.config }}/kobalt doc/examples/hello_world.kb

      - name: Create release archive
        if: github.ref == 'refs/heads/master'
        run: ./premake5 release

      - name: Upload release archive
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: kobalt-prerelease-${{ matrix.osname }}
          path: dist/kobalt-prerelease-${{ matrix.osname }}.tar.gz

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [release]
        cc: [cl]

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua
        uses: xpol/setup-lua@v0.2
        with:
          lua-version: "5.4.0"

      - name: Install premake
        run: |
          Invoke-WebRequest -Uri "https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-windows.zip" -OutFile "premake-5.0.0-alpha15-windows.zip"
          Expand-Archive -DestinationPath . -Path premake-5.0.0-alpha15-windows.zip

      - name: Generate project file
        run: ./premake5 --os=windows vs2019

      - name: Generate version header
        run: lua lib/include/kobalt/version.h.lua "$((get-childitem -name doc/changelog | select-string alpha) -replace "md","${{ github.run_number }}")" > lib/include/kobalt/version.h

      - name: Compile
        run: |
          .\tools\vsenv.ps1
          msbuild kobalt.sln -m -p:CLToolExe=${{ matrix.cc }} -p:Configuration=${{ matrix.config }}

      - name: Say hello world
        run: |
          .\tools\vsenv.ps1
          .\bin\${{ matrix.config }}\kobalt doc\examples\hello_world.kb

      - name: Create release archive
        if: github.ref == 'refs/heads/master'
        run: ./premake5 release

      - name: Upload release archive
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: kobalt-prerelease-windows
          path: dist/kobalt-prerelease-windows.zip
    
  release:
    name: Release
    needs: [build-unix, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: kobalt-prerelease-linux
      
      - uses: actions/download-artifact@v2
        with:
          name: kobalt-prerelease-macosx
      
      - uses: actions/download-artifact@v2
        with:
          name: kobalt-prerelease-windows

      - name: Delete old release
        run: |
          hub release delete latest || true
          git tag -d latest || true
          git push origin --delete latest || true

      - name: Determine the next alpha version number
        run: cat $(ls ./doc/changelog/* | grep alpha) | sed 's/-alpha/-alpha.${{ github.run_number }}/' > release_notes.md

      - name: Create Release
        run: |
          hub release create -p -a kobalt-prerelease-linux.tar.gz -a kobalt-prerelease-macosx.tar.gz -a kobalt-prerelease-windows.zip --file release_notes.md $(ls doc/changelog | grep alpha | sed 's/md/${{ github.run_number }}/')
