name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
    inputs:
      config:
        description: Configuration
        required: true
        default: release
      debug_logs:
        description: Enable debug logging
        required: false
        default:

env:
  CONFIG: release

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        cc: [clang]

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua
        uses: abel0b/setup-lua@v1
        with:
          lua-version: "5.3.5"

      - name: Install premake
        uses: abel0b/setup-premake@v1

      - name: Configure workflow
        if: github.event_name == 'workflow_dispatch'
        run: |
          for log in ${{ github.event.inputs.debug_logs }}; do echo "DEBUG_$log=1" >> $GITHUB_ENV; done
          echo  "CONFIG=${{ github.event.inputs.config }}" >> $GITHUB_ENV

      - name: Generate project file
        run: premake5 gmake2
      
      - name: Generate version header
        run: lua lib/include/kobalt/version.h.lua "$(ls doc/changelog | grep alpha | sed 's/md/${{ github.run_number }}/')" > lib/include/kobalt/version.h

      - name: Compile
        run: make -j$(nproc) CC=${{ matrix.cc }} config=$CONFIG

      - name: Say hello world
        run: ./bin/$CONFIG/kobalt doc/examples/hello_world.kl

      - name: Create release archive
        run: premake5 release

      - name: Upload release archive
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: kobalt-prerelease-${{ matrix.osname }}
          path: dist/kobalt-prerelease-${{ matrix.osname }}.tar.gz


  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [release]
        cc: [cl]

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua
        uses: abel0b/setup-lua@v1
        with:
          lua-version: "5.3.5"

      - name: Install premake
        uses: abel0b/setup-premake@v1

      - name: Configure workflow
        if: github.event_name == 'workflow_dispatch'
        run: |
          foreach($log in "${{ github.event.inputs.debug_logs }}".split(" ")) { echo "DEBUG_$log=1" >> $env:GITHUB_ENV }
          echo  "CONFIG=${{ github.event.inputs.config }}" >> $env:GITHUB_ENV

      - name: Generate project file
        run: premake5 vs2019

      - name: Generate version header
        run: lua lib/include/kobalt/version.h.lua "$((get-childitem -name doc/changelog | select-string alpha) -replace "md","${{ github.run_number }}")" > lib/include/kobalt/version.h

      - name: Compile
        run: |
          .\tools\vsenv.ps1
          msbuild kobalt.sln -m -p:CLToolExe=${{ matrix.cc }} -p:Configuration=$env:CONFIG

      - name: Say hello world
        run: |
          .\tools\vsenv.ps1
          & ".\bin\$env:CONFIG\kobalt" doc\examples\hello_world.kl

      - name: Create release archive
        run: premake5 release

      - name: Upload release archive
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: kobalt-prerelease-windows
          path: dist/kobalt-prerelease-windows.zip
