name: release

on:
  push:
    branches: [ master ]
    tags:
      - '*'
env:
  CONFIG: release

jobs:
  release-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        cc: [clang]
        include:
          - os: ubuntu-20.04
            osname: linux
          - os: macos-10.15
            osname: macos

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua
        uses: abel0b/setup-lua@v1
        with:
          lua-version: "5.3.5"

      - name: Install premake
        uses: abel0b/setup-premake@v1

      - name: Generate project file
        run: premake5 gmake2
      
      - name: Compile
        run: make -j$(nproc) CC=${{ matrix.cc }} config=$CONFIG

      - name: Create release archive
        run: premake5 release

      - name: Upload release archive
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: kobalt-${{ matrix.osname }}
          path: dist/kobalt-${{ matrix.osname }}.tar.gz

  release-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [release]
        cc: [cl]

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua
        uses: abel0b/setup-lua@v1
        with:
          lua-version: "5.3.5"

      - name: Install premake
        uses: abel0b/setup-premake@v1

      - name: Generate project file
        run: premake5 vs2019

      - name: Compile
        run: |
          .\tools\vsenv.ps1
          msbuild kobalt.sln -m -p:CLToolExe=${{ matrix.cc }} -p:Configuration=$env:CONFIG

      - name: Create release archive
        run: premake5 release

      - name: Upload release archive
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: kobalt-windows
          path: dist/kobalt-windows.zip

  release:
    needs: [release-unix, release-windows]

    runs-on: ubuntu-20.04

    if: github.ref == 'refs/heads/master'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: kobalt-linux
      
      - uses: actions/download-artifact@v2
        with:
          name: kobalt-macos
      
      - uses: actions/download-artifact@v2
        with:
          name: kobalt-windows

      - name: Generate release notes
        run: if [[ -f ./doc/changelog/$(git describe --tags --abbrev=0 HEAD).md ]]; then cp ./doc/changelog/$(git describe --tags --abbrev=0 HEAD) .md release_notes.md; else git describe --tags --abbrev=0 HEAD > release_notes.md; fi

      - name: Create Release
        run: |
          hub release create -p -a kobalt-linux.tar.gz -a kobalt-macos.tar.gz -a kobalt-windows.zip --file release_notes.md $(git describe --tags --abbrev=0 HEAD)
