name: test

on: [push, pull_request]

jobs:
  test-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        config: [debug]
        cc: [clang]
        include:
          - os: ubuntu-20.04
            osname: linux
          - os: macos-10.15
            osname: macosx

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua
        uses: abel0b/setup-lua@v1
        with:
          lua-version: "5.3.5"

      - name: Install premake
        uses: abel0b/setup-premake@v1

      - name: Generate project file
        run: ./premake5 --os=${{ matrix.osname }} gmake2
      
      - name: Compile
        run: make -j$(nproc) CC=${{ matrix.cc }} config=${{ matrix.config }}

      - name: Run examples
        run: for example in doc/examples/*.kl; do ./bin/${{ matrix.config }}/kobalt $example; done

  test-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [debug]
        cc: [cl]

    steps:
      - uses: actions/checkout@v2

      - name: Install Lua
        uses: abel0b/setup-lua@v1
        with:
          lua-version: "5.3.5"

      - name: Install premake
        uses: abel0b/setup-premake@v1

      - name: Generate project file
        run: ./premake5 --os=windows vs2019

      - name: Generate version header
        run: lua lib/include/kobalt/version.h.lua "$((get-childitem -name doc/changelog | select-string alpha) -replace "md","${{ github.run_number }}")" > lib/include/kobalt/version.h

      - name: Compile
        run: |
          .\tools\vsenv.ps1
          msbuild kobalt.sln -m -p:CLToolExe=${{ matrix.cc }} -p:Configuration=${{ matrix.config }}

      - name: Run examples
        run: |
          .\tools\vsenv.ps1
          get-childitem doc\examples -filter *.kl | foreach-object { bin\${{ matrix.config }}\kobalt.exe $_.FullName }
