name: test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        ./dev/build.bash test
        ./dev/test.bash
      
  test-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        ./dev/build.bash test
        ./dev/test.bash
